### ISSUE TITLE
Unsure if the calibration calculation used in the code is correct

### ISSUE THREAD

**Issue by ahmed-tkhan** [RobTillaart/INA219#14]
`  calib = round(0.04096 / (_current_LSB * shunt));
`
![image](https://github.com/RobTillaart/INA219/assets/46329434/670e4ac6-5abd-4bc5-9295-26f348234195)

You use **round** in your calculation for the calibration but the datasheet says to use **truncate**. I don't know if this is an oversight or intentional. I'm nitpicking I know.

Thank you for the nice library. 👍

**Comment by RobTillaart** [comment]
Thank you for pointing to this bug. 
This would be a systematic error (in 50% of the cases) so needs to be fixed.
Have you an indication about the impact, in absolute sense?  

> I'm nitpicking I know.

I would call it a decent review, I assume I missed it when implementing and it just stayed in the library since then.

**Comment by RobTillaart** [comment]
Created a develop branch for version 0.3.0
includes the fix + some edits and build-CI update that were pending.

**Comment by RobTillaart** [comment]
There is a problem with the pull request build-CI, one version just builds correctly, the other blocks/freezes.
DO not know the cause, however given that one build is OK you could try the develop branch if you want to.

**Comment by RobTillaart** [comment]
Merged into master and released as 0.3.0
